### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by 1138-4EB** [ghdl/ghdl-language-server#13]
[Dependabot](https://dependabot.com/) is a service for automated dependency updates. It creates pull requests to keep dependencies secure and up-to-date.

> 1. Dependabot checks for updates
> 2. Dependabot opens pull requests
> 3. You review and merge

> Dependabot has been acquired by GitHub and is now free of charge 🎁

I think we should enable it for the `vscode-client` at least. Nonetheless, it is possible to enable it for `ghdl-ls` too.

**Comment by tgingold** [comment]
Worth a try.
For ghdl-ls, the number of dependences is small, and ideally it should only use the standard python library + libghdl.

**Comment by 1138-4EB** [comment]
> Worth a try.

Unfortunately, I cannot enable/install it. We need you to do it, since you are the owner of the organization. First, you need to enable dependabot for the organization (select to enable specific repos only). Then, in GitHub, go to the org's settings and enable `ghdl-language-server` only. Last, specify that the directory for 'JavaScript' is `vscode-client`.

> For ghdl-ls, the number of dependences is small, and ideally it should only use the standard python library + libghdl.

In practice, I think it should have no effect, even if we enable it. This is because there are two dependencies only; one of them is not constrained and the other one is fixed: https://github.com/ghdl/ghdl-language-server/blob/master/ghdl-ls/setup.py#L34-L35

**Comment by 1138-4EB** [comment]
I tried enabling dependabot for my fork: https://github.com/1138-4EB/ghdl-language-server. Since three dependencies are out of date, a PR was created for each of them: https://github.com/1138-4EB/ghdl-language-server/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc. This was expected, because it is shown in david-dm badges (see #16).

However, I think it does not make sense to merge them in my fork and then make a PR here. Specially for future updates, it is desirable to have it enabled here. @tgingold, could you please have a look at it?

**Comment by tgingold** [comment]
Now done.  Thanks!

**Comment by 1138-4EB** [comment]
There it goes! Thank you!

I suggest you 'Squash and merge' these PRs, instead of just merging them.
