### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by FlatAssembler** [ghdl/ghdl-language-server#29]
I have installed ghdl, it's working properly, however, an attempt to "pip install ." gives this error:
`HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/libghdl/`

**Comment by 1138-4EB** [comment]
As explained in https://github.com/ghdl/ghdl-language-server#requirements, you need to install `libghdl-py` first:

```sh
mkdir libghdl-py
cd libghdl-py
curl -fsSL https://codeload.github.com/ghdl/ghdl/tar.gz/master | tar xzf - --strip-components=2 ghdl-master/python

pip3 install .

cd ..

mkdir ghdl-ls
cd ghdl-ls
curl -fsSL https://codeload.github.com/ghdl/ghdl-language-server/tar.gz/master | tar xzf - --strip-components=2 ghdl-language-server-master/ghdl-ls

pip3 install .
```
